# Example configuration for pg-metako distributed PostgreSQL cluster management

# Node identification - This identifies this pg-metako instance
identity:
  node_name: "pg-metako-node1"    # Unique name for this node
  local_db_host: "localhost"      # Local PostgreSQL instance host
  local_db_port: 5432            # Local PostgreSQL instance port
  api_host: "0.0.0.0"            # API host for inter-node communication
  api_port: 8080                 # API port for inter-node communication

# Local PostgreSQL database configuration
local_db:
  name: "postgres-node1"
  host: "localhost"
  port: 5432
  role: "master"                 # Role of the local PostgreSQL instance
  username: "postgres"
  password: "password"
  database: "myapp"

# Other pg-metako nodes in the cluster
cluster_members:
  - node_name: "pg-metako-node2"
    api_host: "192.168.1.102"
    api_port: 8080
    role: "slave"
  
  - node_name: "pg-metako-node3"
    api_host: "192.168.1.103"
    api_port: 8080
    role: "slave"

# Coordination settings for distributed consensus
coordination:
  cluster_mode:
    heartbeat_interval: "10s"
    communication_timeout: "5s"
    failover_timeout: "30s"
    min_consensus_nodes: 2
    local_node_preference: 0.8
  pair_mode:
    enable: true
    failover_delay: "10s"
    failure_threshold: 3

# Health check configuration
health_check:
  interval: "30s"          # How often to check node health
  timeout: "5s"            # Timeout for each health check
  failure_threshold: 3     # Number of consecutive failures before marking node as unhealthy

# Load balancer configuration
load_balancer:
  algorithm: "round_robin" # Options: round_robin, least_connected
  read_timeout: "10s"      # Timeout for read queries
  write_timeout: "10s"     # Timeout for write queries

# Security configuration
security:
  tls_enabled: false
  # cert_file: "/etc/ssl/certs/pg-metako.crt"
  # key_file: "/etc/ssl/private/pg-metako.key"