# Docker-specific configuration for pg-metako PostgreSQL replication management
# This configuration uses Docker service names for container communication

nodes:
  - name: "postgres-master"
    host: "postgres-master"
    port: 5432
    role: "master"
    username: "postgres"
    password: "password"
    database: "myapp"
  
  - name: "postgres-slave1"
    host: "postgres-slave1"
    port: 5432
    role: "slave"
    username: "postgres"
    password: "password"
    database: "myapp"
  
  - name: "postgres-slave2"
    host: "postgres-slave2"
    port: 5432
    role: "slave"
    username: "postgres"
    password: "password"
    database: "myapp"

# Health check configuration
health_check:
  interval: "30s"          # How often to check node health
  timeout: "10s"           # Timeout for each health check (increased for containers)
  failure_threshold: 3     # Number of consecutive failures before marking node as unhealthy

# Load balancer configuration
load_balancer:
  algorithm: "round_robin" # Options: round_robin, least_connected
  read_timeout: "15s"      # Timeout for read queries (increased for containers)
  write_timeout: "15s"     # Timeout for write queries (increased for containers)

# Security configuration (disabled for Docker development)
security:
  tls_enabled: false
  cert_file: ""
  key_file: ""